import type { Report } from 'src/_mock/_report';

import { useState } from 'react';

import Stack from '@mui/material/Stack';
import Button from '@mui/material/Button';
import Popover from '@mui/material/Popover';
import Tooltip from '@mui/material/Tooltip';
import Checkbox from '@mui/material/Checkbox';
import MenuList from '@mui/material/MenuList';
import TableRow from '@mui/material/TableRow';
import TableCell from '@mui/material/TableCell';
import IconButton from '@mui/material/IconButton';
import Typography from '@mui/material/Typography';
import CircularProgress from '@mui/material/CircularProgress';
import MenuItem, { menuItemClasses } from '@mui/material/MenuItem';

import { fDate } from 'src/utils/format-time';

import { Label } from 'src/components/label';
import { Iconify } from 'src/components/iconify';

// ----------------------------------------------------------------------

type ReportTableRowProps = {
  row: Report & { from?: string; to?: string };
  selected: boolean;
  onSelectRow: () => void;
  onDelete?: () => void;
  onRegenerate?: () => void;
  onDownload?: (format: 'pdf' | 'excel') => void;
};

export function ReportTableRow({
  row,
  selected,
  onSelectRow,
  onDelete,
  onRegenerate,
  onDownload,
}: ReportTableRowProps) {
  const [openPopover, setOpenPopover] = useState<HTMLButtonElement | null>(null);

  const handleOpenPopover = (event: React.MouseEvent<HTMLButtonElement>) => {
    setOpenPopover(event.currentTarget);
  };

  const handleClosePopover = () => setOpenPopover(null);

  const getTypeColor = (type: string) => {
    if (type === 'portfolio') return 'primary';
    if (type === 'recovery') return 'success';
    if (type === 'credit') return 'warning';
    if (type === 'compliance') return 'error';
    return 'default' as const;
  };

  const getStatusColor = (status: string) => {
    if (status === 'ready') return 'success';
    if (status === 'generating' || status === 'pending') return 'warning';
    if (status === 'failed') return 'error';
    return 'default' as const;
  };

  const isReady = row.status === 'ready';
  const isGenerating = row.status === 'generating';

  return (
    <>
      <TableRow hover tabIndex={-1} role="checkbox" selected={selected}>
        <TableCell padding="checkbox">
          <Checkbox disableRipple checked={selected} onChange={onSelectRow} />
        </TableCell>

        {/* Report name + date range */}
        <TableCell>
          <Typography variant="subtitle2" noWrap>
            {row.name}
          </Typography>
          {(row.from || row.to) && (
            <Typography variant="caption" color="text.secondary">
              {row.from ? fDate(row.from) : ''} {row.from && row.to ? '–' : ''}{' '}
              {row.to ? fDate(row.to) : ''}
            </Typography>
          )}
          {row.description && !(row.from || row.to) && (
            <Typography variant="caption" color="text.secondary">
              {row.description}
            </Typography>
          )}
        </TableCell>

        {/* Type */}
        <TableCell>
          <Label color={getTypeColor(row.type)}>
            {row.type.charAt(0).toUpperCase() + row.type.slice(1)}
          </Label>
        </TableCell>

        {/* Generated date */}
        <TableCell>
          <Typography variant="body2">
            {row.lastGenerated ? fDate(row.lastGenerated) : '—'}
          </Typography>
        </TableCell>

        {/* Generated by */}
        <TableCell>
          <Typography variant="body2">{row.generatedBy || '—'}</Typography>
        </TableCell>

        {/* Status */}
        <TableCell>
          <Label color={getStatusColor(row.status)} sx={{ gap: 0.5 }}>
            {isGenerating && <CircularProgress size={10} color="inherit" />}
            {row.status === 'generating'
              ? 'Generating'
              : row.status === 'failed'
                ? 'Failed'
                : row.status === 'ready'
                  ? 'Ready'
                  : row.status}
          </Label>
        </TableCell>

        {/* Download buttons + more actions */}
        <TableCell align="right">
          <Stack direction="row" spacing={0.75} justifyContent="flex-end" alignItems="center">
            <Tooltip title={isReady ? 'Download PDF' : 'Report not ready'}>
              <span>
                <Button
                  size="small"
                  variant="outlined"
                  disabled={!isReady}
                  onClick={() => onDownload?.('pdf')}
                  startIcon={<Iconify icon="solar:file-download-bold" width={15} />}
                  sx={{ minWidth: 0, px: 1.25, fontSize: '0.72rem' }}
                >
                  PDF
                </Button>
              </span>
            </Tooltip>

            <Tooltip title={isReady ? 'Download Excel' : 'Report not ready'}>
              <span>
                <Button
                  size="small"
                  variant="outlined"
                  color="success"
                  disabled={!isReady}
                  onClick={() => onDownload?.('excel')}
                  startIcon={<Iconify icon="solar:file-text-bold" width={15} />}
                  sx={{ minWidth: 0, px: 1.25, fontSize: '0.72rem' }}
                >
                  Excel
                </Button>
              </span>
            </Tooltip>

            <IconButton size="small" onClick={handleOpenPopover}>
              <Iconify icon="eva:more-vertical-fill" />
            </IconButton>
          </Stack>
        </TableCell>
      </TableRow>

      <Popover
        open={!!openPopover}
        anchorEl={openPopover}
        onClose={handleClosePopover}
        anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
        transformOrigin={{ vertical: 'top', horizontal: 'right' }}
      >
        <MenuList
          disablePadding
          sx={{
            p: 0.5,
            gap: 0.5,
            width: 150,
            display: 'flex',
            flexDirection: 'column',
            [`& .${menuItemClasses.root}`]: {
              px: 1,
              gap: 2,
              borderRadius: 0.75,
            },
          }}
        >
          <MenuItem
            onClick={() => {
              handleClosePopover();
              onRegenerate?.();
            }}
            disabled={isGenerating}
          >
            <Iconify icon="solar:refresh-bold" />
            Regenerate
          </MenuItem>

          <MenuItem
            onClick={() => {
              handleClosePopover();
              onDelete?.();
            }}
            sx={{ color: 'error.main' }}
          >
            <Iconify icon="solar:trash-bin-trash-bold" />
            Delete
          </MenuItem>
        </MenuList>
      </Popover>
    </>
  );
}
