import type { Report } from 'src/_mock/_report';
import type { SelectChangeEvent } from '@mui/material/Select';

import { useState, useCallback } from 'react';

import Box from '@mui/material/Box';
import Card from '@mui/material/Card';
import Grid from '@mui/material/Grid';
import Stack from '@mui/material/Stack';
import Table from '@mui/material/Table';
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import TableBody from '@mui/material/TableBody';
import Typography from '@mui/material/Typography';
import TableContainer from '@mui/material/TableContainer';
import TablePagination from '@mui/material/TablePagination';

import { DashboardContent } from 'src/layouts/dashboard';

import { Iconify } from 'src/components/iconify';

const REPORT_CATEGORIES = [
  {
    id: 'portfolio',
    name: 'Portfolio Reports',
    description: 'Monthly portfolio performance and metrics',
    icon: '📊',
    count: 0,
  },
  {
    id: 'recovery',
    name: 'Recovery Reports',
    description: 'Aging analysis and recovery tracking',
    icon: '💰',
    count: 0,
  },
  {
    id: 'credit',
    name: 'Credit Reports',
    description: 'Credit appraisal and risk assessment',
    icon: '⚖️',
    count: 0,
  },
  {
    id: 'compliance',
    name: 'Compliance Reports',
    description: 'Regulatory compliance for SECP/SBP',
    icon: '📋',
    count: 0,
  },
];
import { Scrollbar } from 'src/components/scrollbar';

import { TableNoData } from '../table-no-data';
import { ReportTableRow } from '../report-table-row';
import { TableEmptyRows } from '../table-empty-rows';
import { ReportTableHead } from '../report-table-head';
import { ReportTableToolbar } from '../report-table-toolbar';
import { emptyRows, applyFilter, getComparator } from '../utils';

// ----------------------------------------------------------------------

export function ReportView() {
  const [reports, setReports] = useState<Report[]>([]);
  const [filterName, setFilterName] = useState('');
  const [filterType, setFilterType] = useState('all');
  const [page, setPage] = useState(0);
  const [orderBy, setOrderBy] = useState('lastGenerated');
  const [order, setOrder] = useState<'asc' | 'desc'>('desc');
  const [selected, setSelected] = useState<string[]>([]);
  const [rowsPerPage, setRowsPerPage] = useState(5);

  const HEAD_CELLS = [
    { id: 'name', label: 'Report Name' },
    { id: 'type', label: 'Type' },
    { id: 'lastGenerated', label: 'Last Generated' },
    { id: 'generatedBy', label: 'Generated By' },
    { id: 'status', label: 'Status' },
    { id: 'fileSize', label: 'File Size' },
    { id: 'format', label: 'Format' },
  ];

  const handleSort = useCallback(
    (property: string) => {
      const isAsc = orderBy === property && order === 'asc';
      setOrder(isAsc ? 'desc' : 'asc');
      setOrderBy(property);
    },
    [order, orderBy]
  );

  const handleSelectAllRows = useCallback((checked: boolean) => {
    if (checked) {
      const newSelecteds = reports.map((n) => n.id);
      setSelected(newSelecteds);
      return;
    }
    setSelected([]);
  }, []);

  const handleSelectRow = useCallback(
    (id: string) => {
      const selectedIndex = selected.indexOf(id);
      let newSelected: string[] = [];

      if (selectedIndex === -1) {
        newSelected = newSelected.concat(selected, id);
      } else if (selectedIndex === 0) {
        newSelected = newSelected.concat(selected.slice(1));
      } else if (selectedIndex === selected.length - 1) {
        newSelected = newSelected.concat(selected.slice(0, -1));
      } else if (selectedIndex > 0) {
        newSelected = newSelected.concat(
          selected.slice(0, selectedIndex),
          selected.slice(selectedIndex + 1)
        );
      }

      setSelected(newSelected);
    },
    [selected]
  );

  const handleChangePage = useCallback((_event: unknown, newPage: number) => {
    setPage(newPage);
  }, []);

  const handleChangeRowsPerPage = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    setPage(0);
    setRowsPerPage(parseInt(event.target.value, 10));
  }, []);

  const handleFilterByName = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    setPage(0);
    setFilterName(event.target.value);
  }, []);

  const handleFilterByType = useCallback((event: SelectChangeEvent) => {
    setPage(0);
    setFilterType(event.target.value);
  }, []);

  const dataFiltered: Report[] = applyFilter({
    inputData: reports,
    comparator: getComparator(order, orderBy),
    filterName,
    filterType,
  });

  const notFound = !dataFiltered.length && (!!filterName || filterType !== 'all');

  return (
    <DashboardContent>
      <Container maxWidth="xl">
        <Stack direction="row" alignItems="center" justifyContent="space-between" mb={3}>
          <Typography variant="h4">MIS & Regulatory Reports</Typography>
          <Button
            variant="contained"
            color="primary"
            startIcon={<Iconify icon="solar:add-circle-bold" />}
          >
            Generate Report
          </Button>
        </Stack>

        {/* Report Categories */}
        <Grid container spacing={3} sx={{ mb: 3 }}>
          {REPORT_CATEGORIES.map((category) => (
            <Grid key={category.id} size={{ xs: 12, sm: 6, md: 3 }}>
              <Card sx={{ p: 3, height: '100%' }}>
                <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 2 }}>
                  <Box
                    sx={{
                      width: 56,
                      height: 56,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      borderRadius: 2,
                      bgcolor: (theme) => theme.palette.grey[200],
                      fontSize: '1.5rem',
                    }}
                  >
                    {category.icon}
                  </Box>
                  <Box sx={{ flex: 1 }}>
                    <Typography variant="h4" sx={{ mb: 0.5 }}>
                      {category.count}
                    </Typography>
                    <Typography variant="subtitle2" sx={{ mb: 0.5 }}>
                      {category.name}
                    </Typography>
                    <Typography variant="caption" sx={{ color: 'text.secondary' }}>
                      {category.description}
                    </Typography>
                  </Box>
                </Box>
              </Card>
            </Grid>
          ))}
        </Grid>

        {/* Reports Table */}
        <Card>
          <ReportTableToolbar
            numSelected={selected.length}
            filterName={filterName}
            filterType={filterType}
            onFilterName={handleFilterByName}
            onFilterType={handleFilterByType}
          />

          <Scrollbar>
            <TableContainer sx={{ overflow: 'unset' }}>
              <Table sx={{ minWidth: 800 }}>
                <ReportTableHead
                  order={order}
                  orderBy={orderBy}
                  rowCount={reports.length}
                  numSelected={selected.length}
                  onSort={handleSort}
                  onSelectAllRows={handleSelectAllRows}
                  headCells={HEAD_CELLS}
                />
                <TableBody>
                  {dataFiltered
                    .slice(page * rowsPerPage, page * rowsPerPage + rowsPerPage)
                    .map((row) => (
                      <ReportTableRow
                        key={row.id}
                        row={row}
                        selected={selected.includes(row.id)}
                        onSelectRow={() => handleSelectRow(row.id)}
                      />
                    ))}

                  <TableEmptyRows
                    height={68}
                    emptyRows={emptyRows(page, rowsPerPage, dataFiltered.length)}
                  />

                  {notFound && <TableNoData searchQuery={filterName} />}
                </TableBody>
              </Table>
            </TableContainer>
          </Scrollbar>

          <TablePagination
            component="div"
            page={page}
            count={dataFiltered.length}
            rowsPerPage={rowsPerPage}
            onPageChange={handleChangePage}
            rowsPerPageOptions={[5, 10, 25]}
            onRowsPerPageChange={handleChangeRowsPerPage}
          />
        </Card>
      </Container>
    </DashboardContent>
  );
}
